site_name: Repositorio de Yeray Moreno
site_url: https://ymorgil.github.io/systems/

theme:
   name: material
   language: es
   logo: assets/favicon.svg
   palette:
      - scheme: default
        primary: deep purple
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: teal
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Curso 26/27:
        - Pautas: 01curso/01Pautas.md
        - Veyon: 01curso/02Veyon.md
   - Virtualización:
        - Introducción: 02virtual/01introducción.md
        - VirtualBox: 02virtual/02virtualbox.md
        - VMware: 02virtual/03vmware.md
        - Proxmox: 02virtual/04proxmox.md
   - Cloud:
        - Introducción: 03cloud/01introcloud.md
        - AWS: 03cloud/02aws.md
        - EC2: 03cloud/ec2.md
   - Contenedores:
        - Introducción: 04contenedores/00contenedores.md
        - Docker en Windows: 04contenedores/01docker-windows.md # aquí explicas WSL dentro
        - Docker en Linux: 04contenedores/02docker-linux.md
        - Docker Compose: 04contenedores/03docker-compose.md
        - Kubernetes: 04contenedores/04kubernetes.md
   - Scripting:
        - Introducción: 05scripting/01introducción.md
        - Bash: 05scripting/02bash.md
        - Python: 05scripting/03python.md
   - ADD: add/add.md
   - BIU: biu/biu.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css

markdown_extensions:
   - attr_list
   - pymdownx.highlight:
        anchor_linenums: false
        use_pygments: true
   - pymdownx.superfences
   - pymdownx.inlinehilite
