site_name: Repositorio de Yeray Moreno
site_url: https://ymorgil.github.io/systems/

theme:
   name: material
   language: es
   logo: assets/favicon.svg
   features:
      #- navigation.sections
   palette:
      - scheme: default
        primary: deep purple
        accent: indigo
        toggle:
           icon: material/toggle-switch-off-outline
           name: Modo oscuro
      - scheme: slate
        primary: teal
        accent: green
        toggle:
           icon: material/toggle-switch
           name: Modo claro
nav:
   - Inicio: index.md
   - Curso 26/27:
        - Pautas: 01curso/01Pautas.md
        - Máquinas base: 01curso/02maquinasbase.md
        - Veyon: 01curso/03Veyon.md
   - Virtualización:
        - Introducción: 02virtual/01introducción.md
        - VMware: 02virtual/02vmware.md
        - Proxmox: 02virtual/03proxmox.md
   - Contenedores:
        - Docker: 03contenedores/01docker.md
        - Docker práctico: 03contenedores/02docker.md # aquí explicas WSL dentro
        - Kubernetes: 03contenedores/03kubernetes.md
   - Cloud:
        - Introducción: 04cloud/01introcloud.md
        - AWS: 04cloud/02aws.md
        - EC2: 04cloud/ec2.md
   - Scripting:
        - VSCode y Git: 05scripting/01vscode-git.md
        - Scripting: 05scripting/02bash.md
        - PowerShell: 05scripting/05powershell.md
   - Monitorización:
        - Nagios: 06monitor/nagios.md
        - Zabbix: 06monitor/zabbix.md
        - Prometheus y Grafana: 06monitor/prometheus-grafana.md
        - Elastic Stack (ELK): 06monitor/elastic-stack.md
   - Automatización:
        - Ansible: 07automa/ansible.md
        - Vagrant: 07automa/vagrant.md
        - Terraform: 07automa/terraform.md
   - Inteligencia Artificial:
        - Impacto de la IA en sistemas: 08ia/impacto-ia-sistemas.md
        - Entrenar LLM local: 08ia/entrenar-llm-local.md
   - ADD:
        - Introducción: 11add/00-introduccion.md
        - UT01 Directorio: 11add/ut01--Directorio.md
        - UT01 Práctica: 11add/ut01-practica.md
        - UT01 Rúbrica: 11add/ut01-rubrica.md
        - UT02 Procesos: 11add/ut02--Procesos.md
        - UT02 Práctica: 11add/ut02-practica.md
        - UT02 Rúbrica: 11add/ut02-rubrica.md
        - UT03 Automatización: 11add/ut03--Automatizacion.md
        - UT03 Práctica: 11add/ut03-practica.md
        - UT03 Rúbrica: 11add/ut03-rubrica.md
        - UT04 Administración: 11add/ut04--Administracion.md
        - UT04 Práctica: 11add/ut04-practica.md
        - UT04 Rúbrica: 11add/ut04-rubrica.md
        - UT05 Impresión: 11add/ut05--Impresion.md
        - UT05 Práctica: 11add/ut05-practica.md
        - UT05 Rúbrica: 11add/ut05-rubrica.md
        - UT06 Integración: 11add/ut06--Integracion.md
        - UT06 Práctica: 11add/ut06-practica.md
        - UT06 Rúbrica: 11add/ut06-rubrica.md
        - UT07 Scripting: 11add/ut07--Scripting.md
        - UT07 Práctica: 11add/ut07-practica.md
        - UT07 Rúbrica: 11add/ut07-rubrica.md
        - Recursos: 11add/z-recursos.md
   - BIU:
        - Introducción: 12biu/00-introduccion.md
        - UT01 Almacenamiento y Cloud: 12biu/ut01-temario.md
        - UT01 Práctica: 12biu/ut01-practica.md
        - UT01 Rúbrica: 12biu/ut01-rubrica.md
        - UT02 Ecosistema Big Data: 12biu/ut02-temario.md
        - UT02 Práctica: 12biu/ut02-practica.md
        - UT02 Rúbrica: 12biu/ut02-rubrica.md
        - UT03 Integridad de los datos: 12biu/ut03-temario.md
        - UT03 Práctica: 12biu/ut03-practica.md
        - UT03 Rúbrica: 12biu/ut03-rubrica.md
        - UT04 Monitorización: 12biu/ut04-temario.md
        - UT04 Práctica: 12biu/ut04-practica.md
        - UT04 Rúbrica: 12biu/ut04-rubrica.md
        - UT05 Big Data e Inteligencia de Negocio: 12biu/ut05-temario.md
        - UT05 Práctica: 12biu/ut05-practica.md
        - UT05 Rúbrica: 12biu/ut05-rubrica.md
        - Recursos: 12biu/99-recursos.md
   - DJK:
        - Introducción: 13djk/00-introduccion.md
        - UT01 Temario: 13djk/ut01-digitalizacion.md
        - UT01 Práctica: 13djk/ut01-practica.md
        - UT01 Rúbrica: 13djk/ut01-rubrica.md
        - UT02 Temario: 13djk/ut02-thd.md
        - UT02 Práctica: 13djk/ut02-practica.md
        - UT02 Rúbrica: 13djk/ut02-rubrica.md
        - UT03 Temario: 13djk/ut03-cloud.md
        - UT03 Práctica: 13djk/ut03-practica.md
        - UT03 Rúbrica: 13djk/ut03-rubrica.md
        - UT04 Temario: 13djk/ut04-ia.md
        - UT04 Práctica: 13djk/ut04-practica.md
        - UT04 Rúbrica: 13djk/ut04-rubrica.md
        - UT05 Temario: 13djk/ut05-datos-seguridad.md
        - UT05 Práctica: 13djk/ut05-practica.md
        - UT05 Rúbrica: 13djk/ut05-rubrica.md
        - UT06 Temario: 13djk/ut06-proyecto-transformacion.md
        - UT06 Práctica: 13djk/ut06-practica.md
        - UT06 Rúbrica: 13djk/ut06-rubrica.md
        - Recursos: 13djk/recursos.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css

extra_javascript:
   - assets/javascripts/nav-toggle.js

markdown_extensions:
   - admonition
   - attr_list
   - pymdownx.details
   - pymdownx.highlight:
        anchor_linenums: false
        use_pygments: true
   - pymdownx.superfences
   - pymdownx.inlinehilite
