site_name: Repositorio de Yeray Moreno
site_url: https://ymorgil.github.io/systems/

theme:
   name: material
   language: es
   palette:
      - scheme: default
        toggle:
           icon: material/weather-night
           name: Modo oscuro
      - scheme: slate
        toggle:
           icon: material/weather-sunny
           name: Modo claro
nav:
   - Inicio: index.md
   - Curso 26/27:
        - Pautas: curso/01Pautas.md
        - Configuraciones: curso/02Configuraciones.md
        - Veyon: curso/03Veyon.md
   - ADD: add/index.md
   - BIU: biu/index.md

plugins:
   - glightbox

extra_css:
   - assets/css/extra.css
